[package]
name = "queued-task"
version = "0.1.0"
edition = "2021"

[dependencies]
#derive_builder = "0.20.0"
tracing = "0.1"
tokio = { version = "1", features = ["sync", "time", "rt-multi-thread"] }


[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
